[supervisord]
nodaemon=true
[program:php-fpm]
command=/usr/sbin/php-fpm8.3 -F
autostart=true
autorestart=unexpected
exitcodes=0
[program:sonar_poller]
directory=/usr/share/sonar_poller/src
command=/usr/bin/php /usr/share/sonar_poller/src/poller.php
priority=1
autostart=true
autorestart=true
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
